#!/usr/bin/env bash
# This script displays information about subdomains of a given domain.

set -euo pipefail

function get_record_info() {
    local domain=$1
    local subdomain=$2

    local record_type
    record_type=$(nslookup "$subdomain.$domain" | awk '/^'"$subdomain"'\./{print $4}')

    local destination
    destination=$(nslookup "$subdomain.$domain" | awk '/^'"$subdomain"'\./{print $3}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [[ -z $subdomain ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    get_record_info "$domain" "$sub"
done

