#!/usr/bin/env bash
# This script loops from 1 to 10 and displays "Bad Luck" for the 4th loop iteration, "Good Luck" for the 8th loop iteration, and "Best School" for the other iterations.

count=1

while [ $count -le 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "Bad Luck"
  elif [ $count -eq 8 ]
  then
    echo "Good Luck"
  else
    echo "Best School"
  fi
  ((count++))
done

